### ISSUE TITLE
Teste de Baterias

### ISSUE THREAD

**Issue by Fernanda-Marinho** [IEEE-RAS/scratch-sumo#3]
3 baterias foram testadas:

- Uma pegou 3.8V, abaixou pra 3.7 e manteve 
- Uma pegou 3.8V, abaixou pra 3.6, não acho que está mto boa
- Outra carregou bastante (não esperei o carregador apitar), mas pegou 3.9V

* Temos que ver se o carregador é programável.

**Comment by victorcsar** [comment]
+2 baterias testadas:

- As duas vermelhas não passaram de 4.1V
- Ao retirar as duas descarregaram bem rápido e estabilizaram em 3.8

- Temos que verificar novamente se todas estão segurando a carga.

**Comment by victorcsar** [comment]
Ainda tem mais de 15 baterias para testar, é o tempo de carregamento esta em torno de 64 min para cada. Nesse ritmo não sera possível testar todas no período de uma semana.

**Comment by victorcsar** [comment]
seria interessante utilizar o seguidor de linha para verificar como será o comportamento das baterias ja carregadas, ou utilizar outro robô que esteja funcionando.

**Comment by victorcsar** [comment]
[](https://www.youtube.com/watch?v=21b8qLPA_-M&ab_channel=JALASCKARC)

Video de como carregar as baterias, como o carregador é um pouco de ferente, tive que converter v para mah. As baterias pegam 3.6v segundo pesquisei, então aumentei no carregador para 3600 mah. Irei carregar uma para ve se muda alguma coisa.

**Comment by Fernanda-Marinho** [comment]
Mais uma bateria foi carregada hoje (11/05), ficou com 3.9V

**Comment by Fernanda-Marinho** [comment]
Mais uma bateria carrregada, com 3.8V. Ao todo, hj (11/05) temos 8 baterias carregadas: todas entre 3.6 e 3.9 V

**Comment by Fernanda-Marinho** [comment]
![IMG_20230515_120957960.jpg](https://github.com/IEEE-RAS/scratch-sumo/assets/98289412/5122de9b-5454-487c-a520-0d0cdd07cdb3)

Essa bateria tá marcando 3.7V, mas durante o carregamento esquentou muito, tirei com 2h de carregamento. 
O carregador tá apitando bateria baixa pra as baterias com 2.0V e 2.3V 
Ele foi programado pra só carregar acima de 2.4V?

**Comment by Fernanda-Marinho** [comment]
Conferi a bateria que estava esquentando, já ta fria porém baixou de 4.0V para 3.8V
Mais duas baterias (das cinzas) foram carregadas (sem superaquecimento) e ficaram em 4.0V

**Comment by Fernanda-Marinho** [comment]
Ao todo, temos 15 baterias  carregadas: entre 3.6V e 4.0V

**Comment by victorcsar** [comment]
https://www.youtube.com/watch?v=uchFUiXPdQU&ab_channel=noteb00kpc
Esse video mostra como resolver o problema de low battery, tem uma opçao no carreador para chegar a bateria, deixa uns minutos depois da stop e coloca para carregar. O video carrega uma bateria de LIPo mas funciona para as de Lition.

**Comment by victorcsar** [comment]
+1 bateria carregada, demorou 110 min e estava com 2v,  agora pegou 3.9V

**Comment by Fernanda-Marinho** [comment]
Todas as baterias foram carregadas. Estamos começando a testar a duração delas no seguidor de linha

**Comment by Fernanda-Marinho** [comment]
Uma bateria foi testada no seguidor de linha. Durou 40min porém foi de 3.8V para 3.7V
Eu acho que o seguidor de linha possa estar com mal contato ou algum bug. Um dos sensores do seguidor (S5) não ta funcionando

**Comment by Fernanda-Marinho** [comment]
Precisa ver como funciona a função de descarregar a bateria. Pois muito provável que ela dê um valor em Mah e aí olhando quanto a bateria tem (de fábrica) dá pra ter uma noção de quantos por cento de carga ela tem. Se tiver uns 80% de carga ainda, ta boa.

**Comment by Fernanda-Marinho** [comment]
https://pdf1.alldatasheet.com/datasheet-pdf/view/597041/PANASONICBATTERY/NCR18650.html (datasheet de uma das baterias testadas no seguidor de linha), vem com capacidade de fábrica de 2900mAh
Ela vai do max 4.2V (no carregamento)
E min de 2.5V (no descarregamento) pelo q eu entendi. Se tiver errado olhem o pdf e me corrijam
