### ISSUE TITLE
Função Blockly@rduino

### ISSUE THREAD

**Issue by ShinJaca** [IEEE-RAS/scratch-sumo#5]
# Funções a implementar

**Movimento**:
- andar pra frente
- andar pra tras
- andar pra frente e esquerda
- andar à frente e direita
- andar à tras esquerda
- andar à tras direta

**Sensores**:
- Ler distância sensor ultrassom
- ler detecção de borda (sensor IR)

**Comment by Fernanda-Marinho** [comment]
Documentação blockly -> https://developers.google.com/blockly?hl=pt-br&authuser=0
Projeto blockly@rduino -> 
Código-fonte (a ideia é fazer um fork e ir modificando conforme nossas necessidades) -> https://github.com/technologiescollege/Blockly-at-rduino

**Comment by Fernanda-Marinho** [comment]
Achei o código que gera o "Blockly.Arduino", está dentro da pasta "generation". Lá ele contém as funções que traduz o que é Blockly para arduino. 
Tem funções também que adiciona os includes, incializa código e verifica variáveis. 


![Image](https://github.com/IEEE-RAS/scratch-sumo/assets/98289412/7ac93407-3453-4b2f-801c-438929cc60fb)

**Comment by ShinJaca** [comment]
## Rodando localmente

Para rodar localmente usei o método de container com docker, para tanto é interessante criar o arquivo Dockerfile no raiz do repositório do Blockly@rduino contendo a diretiva:
```dockerfile
FROM httpd:2.4
```
em seguida, estando no repositório, construir a imagem ( necessário toda vez que algumas alterações são feitas ):
```bash
docker build -t apache2-server .
```
ao finalizar, iniciar um container com a imagem criada:
```bash
docker run -dit --name blocklyarduino -p 8080:80 --mount type=bind,src=.,dst=/usr/local/apache2/htdocs apache2-server
```
e acessando a aplicação pelo navegador através do endereço localhost:8080 ( nesse caso a porta encaminhada foi 8080, mas pode ser a de preferência ).

**Comment by ShinJaca** [comment]
## Criando uma biblioteca

A aplicação usa basicamente 5 arquivos para configurar uma biblioteca:
- toolbox/toolbox_arduino_1.xml ( ou outro nível )
- lang/pt-br.js ( e outras traduções )
- blocks/arduino_resume.js ( contém a chamada para as definições de bloco )
- blocks/fabricante/fabricante.js ( substituindo o fabricante pelo nome da biblioteca, definições de bloco )
- generators/arduino_resume.js ( chamada para as definições do gerador de codigo )
- generators/fabricante.js (definições dos geradores )

### Toolbox

A toolbox, ou caixa de ferramentas agrupa os blocos disponíveis para o projeto, nesse caso é pensado para servir de agrupamento por nível de dificuldade, mais ou menos abstrato.
Aqui são listados os blocos que aparecem para o usuário: 
```xml
<category name="CAT_NOME" colour="#6D0194">
	<block type="fabricante_nome_do_bloco"></block>
        <block type="fabricante_outro_bloco"></block>
</category>
```

### Traduções

Para que a biblioteca apareça na listagem do nível selecionado, uma tradução para ela deve ser criada nos arquivos de traduções da pasta `lang/BlocklyArduino_blocks`, numa propriedade específica para a biblioteca (categoria), como segue:
```js
Blockly.Msg.CAT_NOME = "Nome da Biblioteca";
```
### TODO
- resumes
- blocks
- generators

**Comment by ShinJaca** [comment]
# Funções de teste

Três funções de teste foram implementadas `moveFrente`, `moveTras` e `parar`, para fazer funcionar, é necessário mesclar os arquivos de configuração e copiar os arquivos de definição de blocos e gerador na sua copia do Blockly@rduino.
